name = "aiken-lang/aiken-gift-card"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/aiken-gift-card'"

[repository]
user = "aiken-lang"
project = "aiken-gift-card"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
