module ElmCardano.TransactionTests exposing (..)

import Bytes exposing (Bytes)
import Bytes.Encode as E
import ElmCardano.Core exposing (NetworkId(..))
import ElmCardano.Transaction.Builder as Tx
import Expect
import Test exposing (Test, describe, test)
import Tests exposing (hex, toBytes)


suite : Test
suite =
    describe "ElmCardano.Transaction"
        [ describe "Transaction.toCbor"
            [ test "basic encode" <|
                \_ ->
                    let
                        transactionId =
                            toBytes
                                [ 0x9D
                                , 0x7F
                                , 0x45
                                , 0x7D
                                , 0xD6
                                , 0x2D
                                , 0x20
                                , 0x62
                                , 0x56
                                , 0x5F
                                , 0x79
                                , 0x4E
                                , 0x42
                                , 0xF9
                                , 0xEC
                                , 0xA4
                                , 0x58
                                , 0xD9
                                , 0xCF
                                , 0xBC
                                , 0xA7
                                , 0x3A
                                , 0x78
                                , 0x93
                                , 0x89
                                , 0x9D
                                , 0x16
                                , 0xF0
                                , 0x2C
                                , 0x2B
                                , 0x36
                                , 0xB6
                                ]
                    in
                    Tx.new Mainnet
                        |> Tx.input { transactionId = transactionId, outputIndex = 0 }
                        |> Tx.input { transactionId = transactionId, outputIndex = 1 }
                        |> Tx.payToAddress (E.sequence [] |> E.encode) 1000000
                        |> Tx.complete
                        |> expect
                            [ 0x84
                            , 0xA9
                            , 0x00
                            , 0x82
                            , 0x82
                            , 0x58
                            , 0x20
                            , 0x9D
                            , 0x7F
                            , 0x45
                            , 0x7D
                            , 0xD6
                            , 0x2D
                            , 0x20
                            , 0x62
                            , 0x56
                            , 0x5F
                            , 0x79
                            , 0x4E
                            , 0x42
                            , 0xF9
                            , 0xEC
                            , 0xA4
                            , 0x58
                            , 0xD9
                            , 0xCF
                            , 0xBC
                            , 0xA7
                            , 0x3A
                            , 0x78
                            , 0x93
                            , 0x89
                            , 0x9D
                            , 0x16
                            , 0xF0
                            , 0x2C
                            , 0x2B
                            , 0x36
                            , 0xB6
                            , 0x00
                            , 0x82
                            , 0x58
                            , 0x20
                            , 0x9D
                            , 0x7F
                            , 0x45
                            , 0x7D
                            , 0xD6
                            , 0x2D
                            , 0x20
                            , 0x62
                            , 0x56
                            , 0x5F
                            , 0x79
                            , 0x4E
                            , 0x42
                            , 0xF9
                            , 0xEC
                            , 0xA4
                            , 0x58
                            , 0xD9
                            , 0xCF
                            , 0xBC
                            , 0xA7
                            , 0x3A
                            , 0x78
                            , 0x93
                            , 0x89
                            , 0x9D
                            , 0x16
                            , 0xF0
                            , 0x2C
                            , 0x2B
                            , 0x36
                            , 0xB6
                            , 0x01
                            , 0x01
                            , 0x82
                            , 0xA3
                            , 0x00
                            , 0x58
                            , 0x1D
                            , 0x70
                            , 0x58
                            , 0x91
                            , 0x44
                            , 0xCC
                            , 0x52
                            , 0x16
                            , 0x15
                            , 0x31
                            , 0x52
                            , 0x37
                            , 0xF1
                            , 0x26
                            , 0x98
                            , 0xF0
                            , 0x63
                            , 0x22
                            , 0x0E
                            , 0xFA
                            , 0x4B
                            , 0xC2
                            , 0xF3
                            , 0x15
                            , 0xB6
                            , 0xC6
                            , 0xE7
                            , 0x18
                            , 0xA6
                            , 0xD5
                            , 0x01
                            , 0x1A
                            , 0x02
                            , 0xFA
                            , 0xF0
                            , 0x80
                            , 0x02
                            , 0x82
                            , 0x01
                            , 0xD8
                            , 0x18
                            , 0x58
                            , 0x22
                            , 0xD8
                            , 0x79
                            , 0x9F
                            , 0x58
                            , 0x1C
                            , 0xDD
                            , 0x4E
                            , 0xDD
                            , 0x90
                            , 0xA2
                            , 0x29
                            , 0x9D
                            , 0xA2
                            , 0x52
                            , 0x50
                            , 0x53
                            , 0xC5
                            , 0xE1
                            , 0x8E
                            , 0x7C
                            , 0x72
                            , 0x62
                            , 0x5F
                            , 0x7C
                            , 0xF9
                            , 0x26
                            , 0xF5
                            , 0x73
                            , 0x11
                            , 0x39
                            , 0xD9
                            , 0x3B
                            , 0xAE
                            , 0xFF
                            , 0x82
                            , 0x58
                            , 0x1D
                            , 0x60
                            , 0xDD
                            , 0x4E
                            , 0xDD
                            , 0x90
                            , 0xA2
                            , 0x29
                            , 0x9D
                            , 0xA2
                            , 0x52
                            , 0x50
                            , 0x53
                            , 0xC5
                            , 0xE1
                            , 0x8E
                            , 0x7C
                            , 0x72
                            , 0x62
                            , 0x5F
                            , 0x7C
                            , 0xF9
                            , 0x26
                            , 0xF5
                            , 0x73
                            , 0x11
                            , 0x39
                            , 0xD9
                            , 0x3B
                            , 0xAE
                            , 0x1A
                            , 0x74
                            , 0x15
                            , 0xFA
                            , 0xBE
                            , 0x02
                            , 0x1A
                            , 0x00
                            , 0x02
                            , 0xC8
                            , 0x1E
                            , 0x0B
                            , 0x58
                            , 0x20
                            , 0xF9
                            , 0x0C
                            , 0xF1
                            , 0x1D
                            , 0x09
                            , 0x59
                            , 0xB9
                            , 0xAF
                            , 0x8E
                            , 0x6F
                            , 0xCE
                            , 0x10
                            , 0x7A
                            , 0xCD
                            , 0x7A
                            , 0x19
                            , 0x6C
                            , 0x21
                            , 0xFA
                            , 0x3A
                            , 0x0D
                            , 0x9F
                            , 0x14
                            , 0x70
                            , 0xA8
                            , 0xCD
                            , 0xEC
                            , 0x90
                            , 0x5D
                            , 0xCC
                            , 0x6D
                            , 0x85
                            , 0x0D
                            , 0x81
                            , 0x82
                            , 0x58
                            , 0x20
                            , 0x9D
                            , 0x7F
                            , 0x45
                            , 0x7D
                            , 0xD6
                            , 0x2D
                            , 0x20
                            , 0x62
                            , 0x56
                            , 0x5F
                            , 0x79
                            , 0x4E
                            , 0x42
                            , 0xF9
                            , 0xEC
                            , 0xA4
                            , 0x58
                            , 0xD9
                            , 0xCF
                            , 0xBC
                            , 0xA7
                            , 0x3A
                            , 0x78
                            , 0x93
                            , 0x89
                            , 0x9D
                            , 0x16
                            , 0xF0
                            , 0x2C
                            , 0x2B
                            , 0x36
                            , 0xB6
                            , 0x01
                            , 0x0E
                            , 0x81
                            , 0x58
                            , 0x1C
                            , 0xDD
                            , 0x4E
                            , 0xDD
                            , 0x90
                            , 0xA2
                            , 0x29
                            , 0x9D
                            , 0xA2
                            , 0x52
                            , 0x50
                            , 0x53
                            , 0xC5
                            , 0xE1
                            , 0x8E
                            , 0x7C
                            , 0x72
                            , 0x62
                            , 0x5F
                            , 0x7C
                            , 0xF9
                            , 0x26
                            , 0xF5
                            , 0x73
                            , 0x11
                            , 0x39
                            , 0xD9
                            , 0x3B
                            , 0xAE
                            , 0x10
                            , 0x82
                            , 0x58
                            , 0x1D
                            , 0x60
                            , 0xDD
                            , 0x4E
                            , 0xDD
                            , 0x90
                            , 0xA2
                            , 0x29
                            , 0x9D
                            , 0xA2
                            , 0x52
                            , 0x50
                            , 0x53
                            , 0xC5
                            , 0xE1
                            , 0x8E
                            , 0x7C
                            , 0x72
                            , 0x62
                            , 0x5F
                            , 0x7C
                            , 0xF9
                            , 0x26
                            , 0xF5
                            , 0x73
                            , 0x11
                            , 0x39
                            , 0xD9
                            , 0x3B
                            , 0xAE
                            , 0x1A
                            , 0x71
                            , 0x19
                            , 0xA6
                            , 0x2F
                            , 0x11
                            , 0x1A
                            , 0x00
                            , 0x04
                            , 0x2C
                            , 0x2D
                            , 0x12
                            , 0x81
                            , 0x82
                            , 0x58
                            , 0x20
                            , 0x51
                            , 0x7B
                            , 0x05
                            , 0x99
                            , 0x59
                            , 0xFC
                            , 0x8E
                            , 0xE5
                            , 0x84
                            , 0x68
                            , 0x9F
                            , 0x71
                            , 0xCF
                            , 0x1D
                            , 0x9B
                            , 0xB9
                            , 0x4F
                            , 0xC3
                            , 0x68
                            , 0x02
                            , 0xAE
                            , 0xC0
                            , 0xFA
                            , 0xA7
                            , 0xFD
                            , 0x96
                            , 0x18
                            , 0x2C
                            , 0x0A
                            , 0xB0
                            , 0x90
                            , 0xC4
                            , 0x00
                            , 0xA2
                            , 0x04
                            , 0x9F
                            , 0xD8
                            , 0x79
                            , 0x80
                            , 0xFF
                            , 0x05
                            , 0x81
                            , 0x84
                            , 0x00
                            , 0x0D
                            , 0x87
                            , 0x98
                            , 0x08
                            , 0x21
                            , 0x9C
                            , 0x11
                            , 0xB1
                            , 0xA0
                            , 0x11
                            , 0x75
                            , 0x0D
                            , 0x5F
                            , 0x5F
                            , 0xF6
                            ]
            ]
        ]


expect : List Int -> Bytes -> Expect.Expectation
expect fixture result =
    result |> hex |> Expect.equal (Just fixture)
